"""Add cascade for registration

Revision ID: 0a73d1811139
Revises: 8b384f6914df
Create Date: 2024-10-27 13:09:10.492395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a73d1811139'
down_revision: Union[str, None] = '8b384f6914df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('registrations_event_id_fkey', 'registrations', type_='foreignkey')
    op.drop_constraint('registrations_visitor_id_fkey', 'registrations', type_='foreignkey')
    op.create_foreign_key(None, 'registrations', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'registrations', 'visitors', ['visitor_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'registrations', type_='foreignkey')
    op.drop_constraint(None, 'registrations', type_='foreignkey')
    op.create_foreign_key('registrations_visitor_id_fkey', 'registrations', 'visitors', ['visitor_id'], ['id'])
    op.create_foreign_key('registrations_event_id_fkey', 'registrations', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###
